name: Workflow commands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow-commands:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{matrix.os}}
    steps:
      - name: Show GITHUB_ENV contents
        run: echo "$GITHUB_ENV"
      - name: Show GITHUB_OUTPUT contents
        run: echo "$GITHUB_OUTPUT"
      - name: Show GITHUB_PATH contents
        run: echo "$GITHUB_PATH"
