name: Scheduled Workflows 2.0

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show the current time
        run: echo "This is the current time ${date}"
