name: Github Secrets

on: push

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        env:
          LOVER: ${{secrets.LOVER}}
        run: echo "Hello $( echo $LOVER | base64)"
